In [2]:
%cd '/home/mojtaba.kananisarche/Zh'

/home/mojtaba.kananisarche/Zh

In [3]:
from typing import Optional, List, Dict
import pandas as pd
from src.utils.file_folder import get_file_paths
import pandas as pd
import os

def _get_train_val_test_file_paths(
    input_path: str,
    primary_column_name: str,
    secondary_column_name: Optional[str] = None,
) -> List[Dict]:

    file_paths = get_file_paths(folder_path=input_path, depth=2, EXT_LIST=[".csv"])
    data = pd.DataFrame()
    data["path"] = file_paths
    data = data[~data['path'].apply(lambda x:os.path.split(x)[1].startswith('video_info'))].reset_index(drop=True)
    data["fold"] = (
        data["path"]
        .apply(lambda x: os.path.basename(x).split("_")[0])
        .astype(int)
        .astype(str)
    )
    data["subject_id"] = (
        data["path"]
        .apply(lambda x: os.path.basename(x).split("_")[1])
        .astype(int)
        .astype(str)
    )
    data = data.sort_values(["fold", "subject_id"]).reset_index(drop=True)

    columns_to_fold_by = data[
        [primary_column_name]
        + ([secondary_column_name] if secondary_column_name else [])
    ]

    train_val_test_file_paths = []
    unique_main_column_values = sorted(
        columns_to_fold_by[primary_column_name].unique()
    )

    if primary_column_name and secondary_column_name:
        for main_column_value in unique_main_column_values:
            corresponding_secondary_value = columns_to_fold_by[
                columns_to_fold_by[primary_column_name] == main_column_value
            ][secondary_column_name].unique()
            assert (
                len(corresponding_secondary_value) == 1
            ), f"Multiple Unique Secondary Values Found For Main Column Value {main_column_value} - {corresponding_secondary_value}"
            corresponding_secondary_value = corresponding_secondary_value[0]

            fold_train_val_test_file_paths = {"info": {}, "paths": {}}

            test_split = columns_to_fold_by[
                columns_to_fold_by[primary_column_name] == main_column_value
            ]
            fold_train_val_test_file_paths["paths"]["test"] = data.loc[
                test_split.index.to_list()
            ]["path"].to_list()
            fold_train_val_test_file_paths["info"]["test"] = {
                f"{primary_column_name}": sorted(
                    test_split[primary_column_name].unique().tolist()
                )
            }

            val_split = columns_to_fold_by[
                (columns_to_fold_by[primary_column_name] != main_column_value)
                & (
                    columns_to_fold_by[secondary_column_name]
                    == corresponding_secondary_value
                )
            ]
            fold_train_val_test_file_paths["paths"]["val"] = data.loc[
                val_split.index.to_list()
            ]["path"].to_list()
            fold_train_val_test_file_paths["info"]["val"] = {
                f"{primary_column_name}": sorted(
                    val_split[primary_column_name].unique().tolist()
                )
            }

            train_split = columns_to_fold_by[
                columns_to_fold_by[secondary_column_name]
                != corresponding_secondary_value
            ]
            fold_train_val_test_file_paths["paths"]["train"] = data.loc[
                train_split.index.to_list()
            ]["path"].to_list()
            fold_train_val_test_file_paths["info"]["train"] = {
                f"{primary_column_name}": sorted(
                    train_split[primary_column_name].unique().tolist()
                )
            }
            train_val_test_file_paths.append(fold_train_val_test_file_paths)

    elif primary_column_name:
        for main_column_value_i in unique_main_column_values:
            for main_column_value_j in unique_main_column_values:
                if main_column_value_i != main_column_value_j:
                    fold_train_val_test_file_paths = {"info": {}, "paths": {}}

                    test_split = columns_to_fold_by[
                        columns_to_fold_by[primary_column_name]
                        == main_column_value_i
                    ]
                    fold_train_val_test_file_paths["paths"]["test"] = data.loc[
                        test_split.index.to_list()
                    ]["path"].to_list()
                    fold_train_val_test_file_paths["info"]["test"] = {
                        f"{primary_column_name}": sorted(
                            test_split[primary_column_name].unique().tolist()
                        )
                    }

                    val_split = columns_to_fold_by[
                        columns_to_fold_by[primary_column_name]
                        == main_column_value_j
                    ]
                    fold_train_val_test_file_paths["paths"]["val"] = data.loc[
                        val_split.index.to_list()
                    ]["path"].to_list()
                    fold_train_val_test_file_paths["info"]["val"] = {
                        f"{primary_column_name}": sorted(
                            val_split[primary_column_name].unique().tolist()
                        )
                    }

                    train_split = columns_to_fold_by[
                        ~columns_to_fold_by[primary_column_name].isin(
                            [main_column_value_i, main_column_value_j]
                        )
                    ]
                    fold_train_val_test_file_paths["paths"]["train"] = data.loc[
                        train_split.index.to_list()
                    ]["path"].to_list()
                    fold_train_val_test_file_paths["info"]["train"] = {
                        f"{primary_column_name}": sorted(
                            train_split[primary_column_name].unique().tolist()
                        )
                    }

                    train_val_test_file_paths.append(fold_train_val_test_file_paths)

    return train_val_test_file_paths

In [4]:
input_directory_path = "/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed"
primary_column_name = 'fold'
secondary_column_name = None
train_val_test_file_paths = _get_train_val_test_file_paths(
    input_path = input_directory_path, 
    primary_column_name = primary_column_name, 
    secondary_column_name = secondary_column_name, 
)

In [5]:
train_val_test_file_paths[0]['paths']['train']

['/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_25_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_25_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_25_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_25_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_25_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_25_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_25_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_25_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_25_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_25_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_25_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_25_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_25_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_25_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_25_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_25_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_25_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_25_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_25_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_25_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_25_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_26_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_26_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_26_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_26_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_26_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_26_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_26_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_26_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_26_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_26_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_26_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_26_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_26_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_26_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_26_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_26_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_26_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_26_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_27_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_27_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_27_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_27_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_27_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_27_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_27_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_27_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_27_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_27_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_27_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_27_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_27_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_27_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_27_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_27_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_27_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_27_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_27_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_27_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_27_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_27_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_27_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_27_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_27_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_27_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_27_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_28_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_28_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_28_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_28_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_28_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_28_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_28_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_28_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_28_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_28_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_28_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_28_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_28_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_28_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_28_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_28_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_28_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_28_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_28_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_28_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_28_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_28_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_28_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_28_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_28_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_28_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_28_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_29_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_29_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_29_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_29_0_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_29_10_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_29_5_30fps_flip_flipcode1_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_29_0_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_29_10_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_29_5_30fps_rotate_angle-5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_29_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_29_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_29_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_29_0_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_29_10_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_29_5_30fps_grayscale_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_29_0_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_29_10_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_29_5_30fps_rotate_angle5_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_29_0_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_29_10_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_29_5_30fps_cropped_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_29_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_29_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_29_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_30_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_30_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv',
 '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_30_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv',

In [8]:
import random
from typing import List, Optional, Dict
from unittest import skip

import numpy as np
import pandas as pd
from keras.src.trainers.data_adapters.py_dataset_adapter import PyDataset
from src.preprocess.reshape import reshape_data_rnn
from src.utils.common import merge_intervals, pop_row
from src.utils.load_data import _extract_headers, load_data


class MyDataGenerator(PyDataset):
    """
    Custom data generator for Keras.
    """

    def __init__(self, 
                 paths                  : List[str],
                 video_info_csv_path    : str,
                 groupby_column         : str = "file_name",
                 sortby_column          : str = "frame",
                 target_column          : str = "target",
                 columns_to_drop        : List[str] = [],
                 batch_size             : int = 32,
                 slice_size             : int = 3000,
                 step_size              : int = 3000,
                 discard_threshold_ratio: float = 0.6,
                 shuffle                : bool = False,
                 **kwargs): 
        """
        Initialization function.  This is where you set up the basic parameters
        of your data generator.
        """
        super().__init__(**kwargs)

        self.paths                   = paths
        self.video_info_csv_path     = video_info_csv_path
        self.pointer                 = 0
        self.groupby_column          = groupby_column
        self.sortby_column           = sortby_column
        self.target_column           = target_column
        self.columns_to_drop         = columns_to_drop
        self.batch_size              = batch_size
        self.slice_size              = slice_size
        self.step_size               = step_size
        self.discard_threshold_ratio = discard_threshold_ratio
        self.shuffle                 = shuffle
        
        self.columns_to_drop_1       = self._get_columns_to_drop_1()
        self.feature_columns         = self._get_feature_columns()
        self.batch_info              = self._get_batch_info(
            video_info_csv_path     = self.video_info_csv_path,
            batch_size              = self.batch_size,
            slice_size              = self.slice_size,
            step_size               = self.step_size,
            groupby_column          = 'path',
            groupby_column_filter   = self.paths,
            counts_column           = 'total_frames',
            discard_threshold_ratio = self.discard_threshold_ratio)

        self.num_slices              = []

        self.on_epoch_end()

    def _get_columns_to_drop_1(self):
        return [
            column_name
            for column_name in self.columns_to_drop
            if column_name not in [self.groupby_column, 
                                   self.sortby_column, 
                                   self.target_column]
        ]
    
    def _get_feature_columns(self):
        return [
            column_name
            for column_name in _extract_headers(self.paths[0])
            if column_name not in 
            self.columns_to_drop + [self.target_column, 
                                    self.sortby_column, 
                                    self.groupby_column]
        ]

    def _get_batch_info(
        self,
        video_info_csv_path : str,
        batch_size : int,
        slice_size: int,
        step_size: Optional[int],
        groupby_column : str = 'path',
        groupby_column_filter : List[str] = [],
        counts_column : str = 'total_frames',
        discard_threshold_ratio: float = 0.6) -> Dict[str, List]:

        info = {
            'counts' : [],
            'batches': [],
        }

        video_info = load_data(video_info_csv_path)
        groupby_column_filter = groupby_column_filter or video_info[groupby_column].unique()
        video_info = video_info[video_info[groupby_column].isin(groupby_column_filter)]
        
        new_rows = []
        for _, row in video_info.iterrows():
            total = row[counts_column]
            start_frame = 0
            while start_frame < total:
                end_frame = min(start_frame + slice_size, total)
                current_slice_size = end_frame - start_frame
                if current_slice_size >= discard_threshold_ratio * slice_size:
                    new_row = row.copy()  # Create a copy to avoid modifying the original row
                    new_row['start_frame'] = start_frame
                    new_row['end_frame'] = end_frame
                    new_rows.append(new_row)
                start_frame += step_size

        video_info_processed = pd.DataFrame(new_rows).reset_index(drop=True)

        for group_identifier, group in video_info_processed.groupby(groupby_column):
            info['counts'].append({groupby_column : group_identifier, 
                                'count' : len(group)})

        for i in range(int(np.ceil(len(video_info_processed)/batch_size))):
            start_index = i * batch_size
            end_index   = min((i+1) * batch_size, len(video_info_processed))
            current_batch_info  = []
            for group_identifier, group in video_info_processed[start_index: end_index].groupby(groupby_column):
                current_batch_info.append(
                    {
                        groupby_column : group_identifier,
                        'raw_intervals' : list(zip(group['start_frame'], group['end_frame'])),
                        'merged_intervals' : merge_intervals(list(zip(group['start_frame'], group['end_frame'])))
                    }
                )
            info['batches'].append(current_batch_info)

        return info
    
    def __len__(self):
        """
        Returns the number of batches per epoch.  Keras uses this to know how many
        times to call `__getitem__` in one epoch.
        """
        assert len(self.batch_info['counts']) == len(self.paths), f"num_slices not calculated properly for all paths. num_slices : {len(self.batch_info['counts'])}, paths : {len(self.paths)}"

        return int(np.ceil(sum([file['count'] for file in self.batch_info['counts']])/self.batch_size))
    
    def _preprocess_data(self, file_data):
        file_data = file_data.drop(self.columns_to_drop_1, axis=1)
        X, y, g = reshape_data_rnn(df                      = file_data, 
                                   feature_columns         = self.feature_columns,
                                   slice_size              = self.slice_size,
                                   step_size               = self.step_size,
                                   groupby_column          = self.groupby_column,
                                   sortby_column           = self.sortby_column,
                                   target_column           = self.target_column,
                                   discard_threshold_ratio = self.discard_threshold_ratio)
        return X, y, g
    
    def on_epoch_end(self):
        """
        Called at the end of each epoch.
        #TODO implement proper shuffling. probably not needed as the batch indices are accessed without order
        """
        pass

    def __data_generation(self, index):
        """
        Generates data containing batch_size samples. This is where the actual data
        loading and preprocessing happens.
        """
        current_batch_info = self.batch_info['batches'][index]
        X, y, g = [], [], []

        for file in current_batch_info:
            file_data = load_data(input_path=file['path'], 
                      skiprows=file['merged_intervals'][0][0],
                      nrows=file['merged_intervals'][0][1] - file['merged_intervals'][0][0])
            X_file, y_file, g_file = self._preprocess_data(file_data=file_data)
            
            # Concatenate to the parent arrays
            X.extend(X_file)
            y.extend(y_file)
            g.extend(g_file)

        return {'X': np.array(X), 'y': np.array(y), 'g': np.array(g)}

    def __getitem__(self, index):
        """
        Generates one batch of data.  The core of the data generator.
        #TODO Calculate class weights based on the name of files and num_slices and return
        """
        print(f"index {index}")
        batch = self.__data_generation(index)
        return (batch['X'], batch['y'])

In [9]:
from keras.src.models.sequential import Sequential
import keras
from keras import layers

def _build_model(input_shape) -> Sequential:
    model = Sequential()
    model.add(layers.Input(shape=(input_shape[0], input_shape[1])))

    # Final output layer
    model.add(layers.Dense(1, activation="linear"))  # Use sigmoid activation

    model.compile(
        optimizer=keras.optimizers.AdamW(
            learning_rate=0.001,
            weight_decay=0.00001,
            # beta_1=beta_1,
            # beta_2=beta_2,
            # epsilon=epsilon
        ),
        loss="mse",
        metrics=["mae"],
    )
    return model

In [10]:
model = _build_model((1000, 128))

In [11]:
input_directory_path = "/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed"
groupby_column, sortby_column, target_column = "file_name", "frame", "target"
video_info_csv_path = os.path.join(input_directory_path,'video_info_1.csv')
columns_to_drop = [
        "file_name",
        "file_name_1",
        "type",
        "frame",
        "fold",
        "subject_id",
    ]
batch_size              = 32
step_size               = 1000
slice_size              = 1000
discard_threshold_ratio = 0.5

train_data_gen = MyDataGenerator(
    paths                   = train_val_test_file_paths[0]['paths']['train'][:50],
    video_info_csv_path     = video_info_csv_path,
    groupby_column          = groupby_column,
    sortby_column           = sortby_column,
    target_column           = target_column,
    columns_to_drop         = columns_to_drop,
    batch_size              = batch_size,
    slice_size              = slice_size,
    step_size               = step_size,
    discard_threshold_ratio = discard_threshold_ratio,
    shuffle                 = True,
    workers                 = 1,
    use_multiprocessing     = False,
)
val_data_gen = MyDataGenerator(
    paths                   = train_val_test_file_paths[0]['paths']['val'][:50],
    video_info_csv_path     = video_info_csv_path,
    groupby_column          = groupby_column,
    sortby_column           = sortby_column,
    target_column           = target_column,
    columns_to_drop         = columns_to_drop,
    batch_size              = batch_size,
    slice_size              = slice_size,
    step_size               = step_size,
    discard_threshold_ratio = discard_threshold_ratio,
    shuffle                 = True,
    workers                 = 1,
    use_multiprocessing     = False,
)

2025-04-28 12:44:09,811 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/video_info_1.csv, data shape: (1575, 3)

2025-04-28 12:44:10,992 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/video_info_1.csv, data shape: (1575, 3)

In [12]:
model.fit(train_data_gen, validation_data=val_data_gen, verbose=1)

index 0

2025-04-28 12:44:14,768 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:44:20,733 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (14000, 135)

index 1

2025-04-28 12:44:22,025 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:44:25,080 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (4506, 135)
2025-04-28 12:44:25,519 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (9000, 135)

index 27

2025-04-28 12:44:28,033 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_25_10_30fps_cropped_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:44:37,194 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_26_0_30fps_cropped_preprocessed.csv, data shape: (12506, 135)
2025-04-28 12:44:37,841 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_26_10_30fps_cropped_preprocessed.csv, data shape: (1000, 135)

index 30
 1/31 ━━━━━━━━━━━━━━━━━━━━ 5:59 12s/step - loss: 55.9149 - mae: 6.6382

2025-04-28 12:44:38,493 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_25_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (10000, 135)
2025-04-28 12:44:39,531 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_25_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (18000, 135)

index 22
 2/31 ━━━━━━━━━━━━━━━━━━━━ 1:14 3s/step - loss: 53.7700 - mae: 6.6009

2025-04-28 12:44:41,452 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_5_30fps_grayscale_preprocessed.csv, data shape: (16000, 135)
2025-04-28 12:44:58,724 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_0_30fps_rotate_angle5_preprocessed.csv, data shape: (16000, 135)

index 0
 3/31 ━━━━━━━━━━━━━━━━━━━━ 4:59 11s/step - loss: 49.3570 - mae: 6.2689

2025-04-28 12:44:59,908 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:45:01,832 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (14000, 135)

index 4
 4/31 ━━━━━━━━━━━━━━━━━━━━ 3:39 8s/step - loss: 46.4982 - mae: 6.0568

2025-04-28 12:45:05,445 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (3000, 135)
2025-04-28 12:45:06,498 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (10000, 135)
2025-04-28 12:45:09,234 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_26_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (18506, 135)

index 19
 5/31 ━━━━━━━━━━━━━━━━━━━━ 3:28 8s/step - loss: 44.1683 - mae: 5.8683

2025-04-28 12:45:11,798 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_25_10_30fps_grayscale_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:45:13,093 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_25_5_30fps_grayscale_preprocessed.csv, data shape: (10000, 135)
2025-04-28 12:45:13,682 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_0_30fps_grayscale_preprocessed.csv, data shape: (4000, 135)

index 13
 6/31 ━━━━━━━━━━━━━━━━━━━━ 2:59 7s/step - loss: 43.7116 - mae: 5.8317

2025-04-28 12:45:14,929 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_25_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (12000, 135)
2025-04-28 12:45:19,627 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_26_10_30fps_rotate_angle-5_preprocessed.csv, data shape: (19995, 135)

index 10
 7/31 ━━━━━━━━━━━━━━━━━━━━ 2:52 7s/step - loss: 43.5764 - mae: 5.8191

2025-04-28 12:45:21,614 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_25_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (10000, 135)
2025-04-28 12:45:25,326 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_26_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (22000, 135)

index 26
 8/31 ━━━━━━━━━━━━━━━━━━━━ 2:41 7s/step - loss: 43.4721 - mae: 5.8211

2025-04-28 12:45:28,126 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_25_5_30fps_cropped_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:45:31,139 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_26_0_30fps_cropped_preprocessed.csv, data shape: (6000, 135)
2025-04-28 12:45:35,715 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_25_5_30fps_rotate_angle5_preprocessed.csv, data shape: (8000, 135)

index 17
 9/31 ━━━━━━━━━━━━━━━━━━━━ 2:39 7s/step - loss: 43.3839 - mae: 5.8268

2025-04-28 12:45:36,688 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_25_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (12000, 135)
2025-04-28 12:45:38,039 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_26_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (20000, 135)

index 2
10/31 ━━━━━━━━━━━━━━━━━━━━ 2:22 7s/step - loss: 43.1823 - mae: 5.8219

2025-04-28 12:45:42,621 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:45:43,750 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (11995, 135)
2025-04-28 12:45:44,337 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (2000, 135)

index 23
11/31 ━━━━━━━━━━━━━━━━━━━━ 2:12 7s/step - loss: 42.9617 - mae: 5.8107

2025-04-28 12:45:45,094 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_25_10_30fps_rotate_angle5_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:45:47,156 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_0_30fps_rotate_angle5_preprocessed.csv, data shape: (2506, 135)
2025-04-28 12:45:47,692 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_10_30fps_rotate_angle5_preprocessed.csv, data shape: (11000, 135)

index 5
12/31 ━━━━━━━━━━━━━━━━━━━━ 2:00 6s/step - loss: 43.0199 - mae: 5.8202

2025-04-28 12:45:53,276 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (15000, 135)
2025-04-28 12:45:55,765 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_26_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (17000, 135)

index 29
13/31 ━━━━━━━━━━━━━━━━━━━━ 1:57 7s/step - loss: 43.2377 - mae: 5.8432

2025-04-28 12:45:56,873 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_25_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (8000, 135)
2025-04-28 12:45:57,914 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/3_25_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:46:00,371 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_25_0_30fps_cropped_preprocessed.csv, data shape: (6000, 135)

index 16
14/31 ━━━━━━━━━━━━━━━━━━━━ 1:48 6s/step - loss: 43.4519 - mae: 5.8642

2025-04-28 12:46:00,826 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_25_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (6000, 135)
2025-04-28 12:46:01,696 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_25_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (5000, 135)
2025-04-28 12:46:02,684 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_26_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (20995, 135)

index 6
15/31 ━━━━━━━━━━━━━━━━━━━━ 1:38 6s/step - loss: 43.6698 - mae: 5.8854

2025-04-28 12:46:04,674 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:46:06,419 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_26_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (3995, 135)
2025-04-28 12:46:07,014 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_26_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (10000, 135)

index 25
16/31 ━━━━━━━━━━━━━━━━━━━━ 1:29 6s/step - loss: 43.7750 - mae: 5.8962

2025-04-28 12:46:07,692 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_25_5_30fps_rotate_angle5_preprocessed.csv, data shape: (10000, 135)
2025-04-28 12:46:08,979 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_5_30fps_rotate_angle5_preprocessed.csv, data shape: (22000, 135)

index 11
17/31 ━━━━━━━━━━━━━━━━━━━━ 1:20 6s/step - loss: 43.8395 - mae: 5.9057

2025-04-28 12:46:10,822 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_25_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (8000, 135)
2025-04-28 12:46:12,610 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_25_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:46:15,283 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_26_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (6000, 135)

index 7
18/31 ━━━━━━━━━━━━━━━━━━━━ 1:14 6s/step - loss: 43.8625 - mae: 5.9123

2025-04-28 12:46:16,301 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_26_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (16000, 135)
2025-04-28 12:46:17,649 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_25_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (16000, 135)

index 28
19/31 ━━━━━━━━━━━━━━━━━━━━ 1:06 6s/step - loss: 43.9040 - mae: 5.9212

2025-04-28 12:46:18,621 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_25_0_30fps_cropped_preprocessed.csv, data shape: (12000, 135)
2025-04-28 12:46:19,874 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/3_26_10_30fps_cropped_preprocessed.csv, data shape: (19995, 135)

index 9
20/31 ━━━━━━━━━━━━━━━━━━━━ 59s 5s/step - loss: 43.9249 - mae: 5.9271

2025-04-28 12:46:21,688 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_25_0_30fps_flip_flipcode1_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:46:24,585 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_26_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (9995, 135)
2025-04-28 12:46:25,515 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_26_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (4000, 135)

index 1
21/31 ━━━━━━━━━━━━━━━━━━━━ 53s 5s/step - loss: 43.9034 - mae: 5.9280

2025-04-28 12:46:26,307 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:46:29,092 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (4506, 135)
2025-04-28 12:46:29,518 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (9000, 135)

index 15
22/31 ━━━━━━━━━━━━━━━━━━━━ 47s 5s/step - loss: 43.9026 - mae: 5.9307

2025-04-28 12:46:30,240 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_25_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (13000, 135)
2025-04-28 12:46:31,640 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_26_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (18506, 135)

index 20
23/31 ━━━━━━━━━━━━━━━━━━━━ 41s 5s/step - loss: 43.8606 - mae: 5.9284

2025-04-28 12:46:33,371 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_0_30fps_grayscale_preprocessed.csv, data shape: (14506, 135)
2025-04-28 12:46:35,024 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_10_30fps_grayscale_preprocessed.csv, data shape: (17000, 135)

index 8
24/31 ━━━━━━━━━━━━━━━━━━━━ 35s 5s/step - loss: 43.7866 - mae: 5.9223

2025-04-28 12:46:36,135 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_25_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (2000, 135)
2025-04-28 12:46:37,129 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_26_0_30fps_flip_flipcode1_preprocessed.csv, data shape: (18506, 135)
2025-04-28 12:46:38,151 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/3_26_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (11000, 135)

index 12
25/31 ━━━━━━━━━━━━━━━━━━━━ 30s 5s/step - loss: 43.6803 - mae: 5.9124

2025-04-28 12:46:42,911 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_25_10_30fps_rotate_angle-5_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:46:50,656 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_26_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (12506, 135)
2025-04-28 12:46:51,200 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_26_10_30fps_rotate_angle-5_preprocessed.csv, data shape: (1000, 135)

index 21
26/31 ━━━━━━━━━━━━━━━━━━━━ 26s 5s/step - loss: 43.5694 - mae: 5.9018

2025-04-28 12:46:52,824 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_25_0_30fps_grayscale_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:46:54,109 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_10_30fps_grayscale_preprocessed.csv, data shape: (3995, 135)
2025-04-28 12:46:54,967 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_26_5_30fps_grayscale_preprocessed.csv, data shape: (10000, 135)

index 18
27/31 ━━━━━━━━━━━━━━━━━━━━ 21s 5s/step - loss: 43.4384 - mae: 5.8893

2025-04-28 12:46:56,233 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_25_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:46:57,742 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/3_26_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (6000, 135)
2025-04-28 12:46:58,306 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/3_25_5_30fps_grayscale_preprocessed.csv, data shape: (8000, 135)

index 3
28/31 ━━━━━━━━━━━━━━━━━━━━ 15s 5s/step - loss: 43.3086 - mae: 5.8778

2025-04-28 12:46:59,733 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_26_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (24000, 135)
2025-04-28 12:47:01,629 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/3_25_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (8000, 135)

index 14
29/31 ━━━━━━━━━━━━━━━━━━━━ 10s 5s/step - loss: 43.1709 - mae: 5.8665

2025-04-28 12:47:02,884 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_25_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (6000, 135)
2025-04-28 12:47:10,111 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/3_26_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (26000, 135)

index 24
30/31 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - loss: 43.0220 - mae: 5.8545

2025-04-28 12:47:13,981 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_25_0_30fps_rotate_angle5_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:47:15,467 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_10_30fps_rotate_angle5_preprocessed.csv, data shape: (9995, 135)
2025-04-28 12:47:16,135 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/3_26_5_30fps_rotate_angle5_preprocessed.csv, data shape: (4000, 135)

31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5s/step - loss: 42.8650 - mae: 5.8412index 0

2025-04-28 12:47:18,238 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:47:24,391 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (14000, 135)

index 1

2025-04-28 12:47:26,055 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (4615, 135)
2025-04-28 12:47:35,671 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (20620, 135)
2025-04-28 12:47:37,662 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (6000, 135)

index 0

2025-04-28 12:47:38,831 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:47:39,909 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (14000, 135)

index 1

2025-04-28 12:47:41,125 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (4615, 135)
2025-04-28 12:47:41,896 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (20620, 135)
2025-04-28 12:47:43,229 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (6000, 135)

index 2

2025-04-28 12:47:44,153 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (12000, 135)
2025-04-28 12:47:51,879 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18690, 135)
2025-04-28 12:47:53,199 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (1000, 135)

index 3

2025-04-28 12:47:54,270 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18840, 135)
2025-04-28 12:47:55,995 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (13000, 135)

index 4

2025-04-28 12:47:57,378 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (5000, 135)
2025-04-28 12:48:03,544 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (18615, 135)
2025-04-28 12:48:05,334 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (8000, 135)

index 5

2025-04-28 12:48:06,150 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (12620, 135)
2025-04-28 12:48:07,729 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:48:08,942 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (1000, 135)

index 6

2025-04-28 12:48:09,851 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (17690, 135)
2025-04-28 12:48:11,608 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (14000, 135)

index 7

2025-04-28 12:48:12,547 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (5840, 135)
2025-04-28 12:48:13,710 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_14_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (18690, 135)
2025-04-28 12:48:16,751 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_14_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (7000, 135)

index 8

2025-04-28 12:48:18,761 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_0_30fps_flip_flipcode1_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:48:20,238 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (1000, 135)
2025-04-28 12:48:23,419 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_14_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (12840, 135)

index 9

2025-04-28 12:48:26,283 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (17615, 135)
2025-04-28 12:48:27,998 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (14000, 135)

index 10

2025-04-28 12:48:28,956 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (6620, 135)
2025-04-28 12:48:29,832 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_14_0_30fps_flip_flipcode1_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:48:31,225 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (7000, 135)

index 11

2025-04-28 12:48:32,010 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (11000, 135)
2025-04-28 12:48:33,530 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_10_30fps_rotate_angle-5_preprocessed.csv, data shape: (18615, 135)
2025-04-28 12:48:35,107 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (2000, 135)

index 12

2025-04-28 12:48:36,161 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (18620, 135)
2025-04-28 12:48:39,672 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (13000, 135)

index 13

2025-04-28 12:48:40,514 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (5000, 135)
2025-04-28 12:48:41,671 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_10_30fps_rotate_angle-5_preprocessed.csv, data shape: (18690, 135)
2025-04-28 12:48:43,121 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (8000, 135)

index 14

2025-04-28 12:48:44,337 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (20000, 135)
2025-04-28 12:48:46,100 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (11840, 135)

index 15

2025-04-28 12:48:46,891 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (620, 135)
2025-04-28 12:48:50,043 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_14_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:48:51,991 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_14_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (13000, 135)

index 16

2025-04-28 12:48:52,835 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (6000, 135)
2025-04-28 12:48:53,398 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_14_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (5690, 135)
2025-04-28 12:48:56,252 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_14_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (19840, 135)

index 17

2025-04-28 12:48:58,264 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (12000, 135)
2025-04-28 12:49:00,468 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (18615, 135)
2025-04-28 12:49:01,966 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_0_30fps_grayscale_preprocessed.csv, data shape: (1000, 135)

index 18

2025-04-28 12:49:02,972 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_0_30fps_grayscale_preprocessed.csv, data shape: (17000, 135)
2025-04-28 12:49:06,457 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_10_30fps_grayscale_preprocessed.csv, data shape: (15000, 135)

index 19

2025-04-28 12:49:08,092 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_10_30fps_grayscale_preprocessed.csv, data shape: (3615, 135)
2025-04-28 12:49:09,102 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_5_30fps_grayscale_preprocessed.csv, data shape: (20620, 135)
2025-04-28 12:49:13,245 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_0_30fps_grayscale_preprocessed.csv, data shape: (7000, 135)

index 20

2025-04-28 12:49:14,621 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_0_30fps_grayscale_preprocessed.csv, data shape: (11000, 135)
2025-04-28 12:49:16,264 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_10_30fps_grayscale_preprocessed.csv, data shape: (18690, 135)
2025-04-28 12:49:18,490 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_5_30fps_grayscale_preprocessed.csv, data shape: (2000, 135)

index 21

2025-04-28 12:49:22,858 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_5_30fps_grayscale_preprocessed.csv, data shape: (17840, 135)
2025-04-28 12:49:24,806 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_5_30fps_rotate_angle5_preprocessed.csv, data shape: (14000, 135)

index 22

2025-04-28 12:49:26,694 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_13_0_30fps_rotate_angle5_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:49:28,198 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_13_10_30fps_rotate_angle5_preprocessed.csv, data shape: (8000, 135)
2025-04-28 12:49:28,895 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_5_30fps_rotate_angle5_preprocessed.csv, data shape: (5840, 135)

index 23

2025-04-28 12:49:29,587 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_13_10_30fps_rotate_angle5_preprocessed.csv, data shape: (10615, 135)
2025-04-28 12:49:31,100 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_13_5_30fps_rotate_angle5_preprocessed.csv, data shape: (20620, 135)

index 24

2025-04-28 12:49:33,294 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_0_30fps_rotate_angle5_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:49:34,491 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_10_30fps_rotate_angle5_preprocessed.csv, data shape: (14000, 135)

index 25

2025-04-28 12:49:37,050 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_13_0_30fps_cropped_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:49:38,305 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_13_10_30fps_cropped_preprocessed.csv, data shape: (9000, 135)
2025-04-28 12:49:38,989 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_10_30fps_rotate_angle5_preprocessed.csv, data shape: (4690, 135)

index 26

2025-04-28 12:49:39,620 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_13_10_30fps_cropped_preprocessed.csv, data shape: (9615, 135)
2025-04-28 12:49:41,006 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_13_5_30fps_cropped_preprocessed.csv, data shape: (20620, 135)
2025-04-28 12:49:42,756 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_14_0_30fps_cropped_preprocessed.csv, data shape: (1000, 135)

index 27

2025-04-28 12:49:46,618 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_14_0_30fps_cropped_preprocessed.csv, data shape: (17000, 135)
2025-04-28 12:49:48,536 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_14_10_30fps_cropped_preprocessed.csv, data shape: (15000, 135)

index 28

2025-04-28 12:49:50,268 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/2_13_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:49:51,505 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/2_13_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (10000, 135)
2025-04-28 12:49:52,189 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_14_10_30fps_cropped_preprocessed.csv, data shape: (3690, 135)

index 29

2025-04-28 12:49:52,774 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/2_13_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (8615, 135)
2025-04-28 12:49:53,816 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/2_13_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (20620, 135)

31/31 ━━━━━━━━━━━━━━━━━━━━ 329s 11s/step - loss: 42.7179 - mae: 5.8287 - val_loss: 34.3734 - val_mae: 5.1544

In [15]:
from src.utils.report import report

In [20]:
x = model.predict(val_data_gen)

index 0

2025-04-28 12:59:40,692 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:59:43,363 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (14000, 135)

index 1

2025-04-28 12:59:44,290 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (4615, 135)
2025-04-28 12:59:47,146 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (20620, 135)
2025-04-28 12:59:48,679 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (6000, 135)

index 0

2025-04-28 12:59:49,745 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 12:59:50,775 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (14000, 135)

index 1
 1/30 ━━━━━━━━━━━━━━━━━━━━ 1:08 2s/step

2025-04-28 12:59:51,691 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (4615, 135)
2025-04-28 12:59:52,441 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (20620, 135)
2025-04-28 12:59:53,515 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (6000, 135)

index 2
 2/30 ━━━━━━━━━━━━━━━━━━━━ 1:06 2s/step

2025-04-28 12:59:54,312 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (12000, 135)
2025-04-28 12:59:57,640 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18690, 135)
2025-04-28 12:59:58,498 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (1000, 135)

index 3
 3/30 ━━━━━━━━━━━━━━━━━━━━ 1:36 4s/step

2025-04-28 12:59:59,245 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_14_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18840, 135)
2025-04-28 13:00:01,514 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (13000, 135)

index 4
 4/30 ━━━━━━━━━━━━━━━━━━━━ 1:32 4s/step

2025-04-28 13:00:02,514 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (5000, 135)
2025-04-28 13:00:09,790 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (18615, 135)
2025-04-28 13:00:11,097 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (8000, 135)

index 5
 5/30 ━━━━━━━━━━━━━━━━━━━━ 2:04 5s/step

2025-04-28 13:00:11,919 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_13_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (12620, 135)
2025-04-28 13:00:13,125 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_0_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (18000, 135)
2025-04-28 13:00:14,026 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (1000, 135)

index 6
 6/30 ━━━━━━━━━━━━━━━━━━━━ 1:48 5s/step

2025-04-28 13:00:15,376 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_10_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (17690, 135)
2025-04-28 13:00:17,509 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (14000, 135)

index 7
 7/30 ━━━━━━━━━━━━━━━━━━━━ 1:42 4s/step

2025-04-28 13:00:18,421 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha0.7_beta0/2_14_5_30fps_contrast_alpha0.7_beta0_preprocessed.csv, data shape: (5840, 135)
2025-04-28 13:00:19,318 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_14_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (18690, 135)
2025-04-28 13:00:21,805 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_14_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (7000, 135)

index 8
 8/30 ━━━━━━━━━━━━━━━━━━━━ 1:36 4s/step

2025-04-28 13:00:22,789 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_0_30fps_flip_flipcode1_preprocessed.csv, data shape: (18000, 135)
2025-04-28 13:00:23,623 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (1000, 135)
2025-04-28 13:00:24,675 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_14_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (12840, 135)

index 9
 9/30 ━━━━━━━━━━━━━━━━━━━━ 1:28 4s/step

2025-04-28 13:00:26,799 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_10_30fps_flip_flipcode1_preprocessed.csv, data shape: (17615, 135)
2025-04-28 13:00:28,027 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (14000, 135)

index 10
10/30 ━━━━━━━━━━━━━━━━━━━━ 1:22 4s/step

2025-04-28 13:00:29,030 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_13_5_30fps_flip_flipcode1_preprocessed.csv, data shape: (6620, 135)
2025-04-28 13:00:29,914 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/flip_flipcode1/2_14_0_30fps_flip_flipcode1_preprocessed.csv, data shape: (18000, 135)
2025-04-28 13:00:30,955 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (7000, 135)

index 11
11/30 ━━━━━━━━━━━━━━━━━━━━ 1:15 4s/step

2025-04-28 13:00:31,664 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (11000, 135)
2025-04-28 13:00:33,092 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_10_30fps_rotate_angle-5_preprocessed.csv, data shape: (18615, 135)
2025-04-28 13:00:34,280 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (2000, 135)

index 12
12/30 ━━━━━━━━━━━━━━━━━━━━ 1:10 4s/step

2025-04-28 13:00:35,213 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_13_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (18620, 135)
2025-04-28 13:00:37,682 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (13000, 135)

index 13
13/30 ━━━━━━━━━━━━━━━━━━━━ 1:06 4s/step

2025-04-28 13:00:38,675 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_0_30fps_rotate_angle-5_preprocessed.csv, data shape: (5000, 135)
2025-04-28 13:00:39,550 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_10_30fps_rotate_angle-5_preprocessed.csv, data shape: (18690, 135)
2025-04-28 13:00:40,747 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (8000, 135)

index 14
14/30 ━━━━━━━━━━━━━━━━━━━━ 1:01 4s/step

2025-04-28 13:00:42,026 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (20000, 135)
2025-04-28 13:00:45,054 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle-5/2_14_5_30fps_rotate_angle-5_preprocessed.csv, data shape: (11840, 135)

index 15
15/30 ━━━━━━━━━━━━━━━━━━━━ 57s 4s/step

2025-04-28 13:00:45,815 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (620, 135)
2025-04-28 13:00:49,067 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_14_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (18000, 135)
2025-04-28 13:00:50,397 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_14_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (13000, 135)

index 16
16/30 ━━━━━━━━━━━━━━━━━━━━ 55s 4s/step

2025-04-28 13:00:51,316 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (6000, 135)
2025-04-28 13:00:51,923 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_14_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (5690, 135)
2025-04-28 13:00:53,683 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_14_5_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (19840, 135)

index 17
17/30 ━━━━━━━━━━━━━━━━━━━━ 51s 4s/step

2025-04-28 13:00:55,325 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_0_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (12000, 135)
2025-04-28 13:00:57,294 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha1.2_beta10/2_13_10_30fps_brightness_alpha1.2_beta10_preprocessed.csv, data shape: (18615, 135)
2025-04-28 13:00:58,408 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_0_30fps_grayscale_preprocessed.csv, data shape: (1000, 135)

index 18
18/30 ━━━━━━━━━━━━━━━━━━━━ 47s 4s/step

2025-04-28 13:01:00,935 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_0_30fps_grayscale_preprocessed.csv, data shape: (17000, 135)
2025-04-28 13:01:07,670 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_10_30fps_grayscale_preprocessed.csv, data shape: (15000, 135)

index 19
19/30 ━━━━━━━━━━━━━━━━━━━━ 46s 4s/step

2025-04-28 13:01:08,648 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_10_30fps_grayscale_preprocessed.csv, data shape: (3615, 135)
2025-04-28 13:01:09,559 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_13_5_30fps_grayscale_preprocessed.csv, data shape: (20620, 135)
2025-04-28 13:01:12,769 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_0_30fps_grayscale_preprocessed.csv, data shape: (7000, 135)

index 20
20/30 ━━━━━━━━━━━━━━━━━━━━ 42s 4s/step

2025-04-28 13:01:16,425 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_0_30fps_grayscale_preprocessed.csv, data shape: (11000, 135)
2025-04-28 13:01:17,999 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_10_30fps_grayscale_preprocessed.csv, data shape: (18690, 135)
2025-04-28 13:01:19,908 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_5_30fps_grayscale_preprocessed.csv, data shape: (2000, 135)

index 21
21/30 ━━━━━━━━━━━━━━━━━━━━ 39s 4s/step

2025-04-28 13:01:23,844 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/grayscale/2_14_5_30fps_grayscale_preprocessed.csv, data shape: (17840, 135)
2025-04-28 13:01:25,020 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_5_30fps_rotate_angle5_preprocessed.csv, data shape: (14000, 135)

index 22
22/30 ━━━━━━━━━━━━━━━━━━━━ 35s 4s/step

2025-04-28 13:01:26,237 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_13_0_30fps_rotate_angle5_preprocessed.csv, data shape: (18000, 135)
2025-04-28 13:01:27,218 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_13_10_30fps_rotate_angle5_preprocessed.csv, data shape: (8000, 135)
2025-04-28 13:01:27,900 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_5_30fps_rotate_angle5_preprocessed.csv, data shape: (5840, 135)

index 23
23/30 ━━━━━━━━━━━━━━━━━━━━ 30s 4s/step

2025-04-28 13:01:28,531 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_13_10_30fps_rotate_angle5_preprocessed.csv, data shape: (10615, 135)
2025-04-28 13:01:29,677 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_13_5_30fps_rotate_angle5_preprocessed.csv, data shape: (20620, 135)

index 24
24/30 ━━━━━━━━━━━━━━━━━━━━ 25s 4s/step

2025-04-28 13:01:31,120 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_0_30fps_rotate_angle5_preprocessed.csv, data shape: (18000, 135)
2025-04-28 13:01:32,279 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_10_30fps_rotate_angle5_preprocessed.csv, data shape: (14000, 135)

index 25
25/30 ━━━━━━━━━━━━━━━━━━━━ 21s 4s/step

2025-04-28 13:01:35,186 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_13_0_30fps_cropped_preprocessed.csv, data shape: (18000, 135)
2025-04-28 13:01:36,709 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_13_10_30fps_cropped_preprocessed.csv, data shape: (9000, 135)
2025-04-28 13:01:37,366 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/rotate_angle5/2_14_10_30fps_rotate_angle5_preprocessed.csv, data shape: (4690, 135)

index 26
26/30 ━━━━━━━━━━━━━━━━━━━━ 16s 4s/step

2025-04-28 13:01:38,036 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_13_10_30fps_cropped_preprocessed.csv, data shape: (9615, 135)
2025-04-28 13:01:39,155 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_13_5_30fps_cropped_preprocessed.csv, data shape: (20620, 135)
2025-04-28 13:01:40,067 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_14_0_30fps_cropped_preprocessed.csv, data shape: (1000, 135)

index 27
27/30 ━━━━━━━━━━━━━━━━━━━━ 12s 4s/step

2025-04-28 13:01:42,793 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_14_0_30fps_cropped_preprocessed.csv, data shape: (17000, 135)
2025-04-28 13:01:44,558 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_14_10_30fps_cropped_preprocessed.csv, data shape: (15000, 135)

index 28
28/30 ━━━━━━━━━━━━━━━━━━━━ 8s 4s/step

2025-04-28 13:01:46,581 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/2_13_0_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (18000, 135)
2025-04-28 13:01:48,047 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/2_13_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (10000, 135)
2025-04-28 13:01:48,727 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/cropped/2_14_10_30fps_cropped_preprocessed.csv, data shape: (3690, 135)

index 29
29/30 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step

2025-04-28 13:01:49,271 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/2_13_10_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (8615, 135)
2025-04-28 13:01:50,243 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/contrast_alpha1.5_beta0/2_13_5_30fps_contrast_alpha1.5_beta0_preprocessed.csv, data shape: (20620, 135)

30/30 ━━━━━━━━━━━━━━━━━━━━ 122s 4s/step

In [23]:
x.flatten()

array([1.9571533 , 1.2991314 , 1.1405528 , ..., 0.02952561, 0.02952561,
       0.02952561], dtype=float32)

In [ ]:
y_val_pred, val_report = report(
    model=model,
    x=val_data_gen,
    y=val_data_gen.data["y"].to_list(),
    group_identifiers=val_data_gen.data["g"].to_list(),
    unique_classes=list(self.mapping.values()),
)

2025-04-28 08:18:20,004 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/video_info_1.csv, data shape: (1575, 3)

,file_name,path,total_frames
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156
1,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18362
2,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18519
3,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,19954
4,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,16820
...,...,...,...
1570,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18206
1571,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,17645
1572,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18081
1573,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,20620
1574,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18333

In [ ]:
from src.utils.common import merge_intervals
from typing import Optional, Dict
from src.utils.load_data import _extract_headers, load_data
import pandas as pd
import numpy as np

def get_batch_info(
    video_info_csv_path : str,
    batch_size : int,
    slice_size: int,
    step_size: Optional[int],
    groupby_column : str = 'path',
    counts_column : str = 'total_frames',
    discard_threshold_ratio: float = 0.6) -> Dict:

    info = {
        'counts' : [],
        'batch' : [],
    }

    video_info = load_data(video_info_csv_path)
    
    new_rows = []
    for _, row in video_info.iterrows():
        total = row[counts_column]
        start_frame = 0
        while start_frame < total:
            end_frame = min(start_frame + slice_size, total)
            current_slice_size = end_frame - start_frame
            if current_slice_size >= discard_threshold_ratio * slice_size:
                new_row = row.copy()  # Create a copy to avoid modifying the original row
                new_row['start_frame'] = start_frame
                new_row['end_frame'] = end_frame
                new_rows.append(new_row)
            start_frame += step_size

    video_info_processed = pd.DataFrame(new_rows).reset_index(drop=True)

    for group_identifier, group in video_info_processed.groupby(groupby_column):
        info['counts'].append({groupby_column : group_identifier, 
                               'count' : len(group)})

    for i in range(int(np.ceil(len(video_info_processed)/batch_size))):
        start_index = i * batch_size
        end_index   = min((i+1) * batch_size, len(video_info_processed))
        current_batch_info  = []
        for group_identifier, group in video_info_processed[start_index: end_index].groupby(groupby_column):
            current_batch_info.append(
                {
                    groupby_column : group_identifier,
                    'raw_intervals' : list(zip(group['start_frame'], group['end_frame'])),
                    'merged_intervals' : merge_intervals(list(zip(group['start_frame'], group['end_frame'])))
                }
            )
        info['batch'].append(current_batch_info)

    return info

In [70]:
import os 

input_directory_path = "/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed"
video_info_csv_path = os.path.join(input_directory_path,'video_info_1.csv')

a, b = get_batch_info(
    video_info_csv_path = video_info_csv_path,
    batch_size = 32,
    slice_size= 1000,
    step_size= 1000,
    groupby_column = 'path',
    counts_column = 'total_frames',
    discard_threshold_ratio = 0.5)

2025-04-28 10:26:10,766 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/video_info_1.csv, data shape: (1575, 3)

In [71]:
b['batch']

[[{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_08_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(0, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_09_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000)],
   'merged_intervals': [(0, 14000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_03_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 18519)],
   'merged_intervals': [(0, 18519)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_09_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000)],
   'merged_intervals': [(0, 9000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_09_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(14000, 18000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_04_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000), (1000, 2000), (2000, 3000), (3000, 4000)],
   'merged_intervals': [(0, 4000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_09_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 19000),
    (19000, 19954)],
   'merged_intervals': [(9000, 19954)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 16820)],
   'merged_intervals': [(0, 16820)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_03_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000), (1000, 2000), (2000, 3000)],
   'merged_intervals': [(0, 3000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_04_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(4000, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000)],
   'merged_intervals': [(0, 15000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_03_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(3000, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000)],
   'merged_intervals': [(0, 17000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_04_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(0, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_12_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(17000, 18000), (18000, 18729)],
   'merged_intervals': [(17000, 18729)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000)],
   'merged_intervals': [(0, 12000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_06_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000)],
   'merged_intervals': [(0, 13000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 19000)],
   'merged_intervals': [(12000, 19000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000)],
   'merged_intervals': [(0, 12000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_21_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(0, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 19000)],
   'merged_intervals': [(12000, 19000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000)],
   'merged_intervals': [(0, 7000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 19000),
    (19000, 19664)],
   'merged_intervals': [(0, 19664)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_29_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 14711)],
   'merged_intervals': [(7000, 14711)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000), (1000, 2000), (2000, 3000), (3000, 4000)],
   'merged_intervals': [(0, 4000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_02_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000)],
   'merged_intervals': [(0, 16000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 19000),
    (19000, 20000)],
   'merged_intervals': [(4000, 20000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_02_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(16000, 17000), (17000, 18000)],
   'merged_intervals': [(16000, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 18627)],
   'merged_intervals': [(0, 18627)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000)],
   'merged_intervals': [(0, 11000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(0, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(11000, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000)],
   'merged_intervals': [(0, 7000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_25_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(0, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/3_30_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 19000),
    (19000, 20000),
    (20000, 20865)],
   'merged_intervals': [(7000, 20865)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000)],
   'merged_intervals': [(0, 14000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(0, 18000)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 17986)],
   'merged_intervals': [(14000, 17986)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_06_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000)],
   'merged_intervals': [(0, 9000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 18615)],
   'merged_intervals': [(0, 18615)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_06_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000)],
   'merged_intervals': [(9000, 18000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000), (1000, 2000)],
   'merged_intervals': [(0, 2000)]},
  {'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/2_13_5_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(0, 1000),
    (1000, 2000),
    (2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 19000),
    (19000, 20000),
    (20000, 20620)],
   'merged_intervals': [(0, 20620)]}],
 [{'path': '/work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_11_0_30fps_brightness_alpha0.8_beta-10_preprocessed.csv',
   'raw_intervals': [(2000, 3000),
    (3000, 4000),
    (4000, 5000),
    (5000, 6000),
    (6000, 7000),
    (7000, 8000),
    (8000, 9000),
    (9000, 10000),
    (10000, 11000),
    (11000, 12000),
    (12000, 13000),
    (13000, 14000),
    (14000, 15000),
    (15000, 16000),
    (16000, 17000),
    (17000, 18000),
    (18000, 18854)],
   'merged_intervals': [(2000, 18854)]},

In [40]:
a[::32]

,file_name,path,total_frames,start_frame,end_frame
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,0,1000
32,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18362,14000,15000
64,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,19954,10000,11000

In [36]:
list(zip(i['start_frame'], i['end_frame']))

[(0, 1000),
 (1000, 2000),
 (2000, 3000),
 (3000, 4000),
 (4000, 5000),
 (5000, 6000),
 (6000, 7000),
 (7000, 8000),
 (8000, 9000),
 (9000, 10000),
 (10000, 11000),
 (11000, 12000),
 (12000, 13000),
 (13000, 14000)]

In [114]:
def merge_intervals(intervals):
    # First, sort the intervals by their start value
    intervals = sorted(intervals, key=lambda x: x[0])
    
    merged = []
    for interval in intervals:
        if not merged:
            merged.append(interval)
        else:
            last = merged[-1]
            if interval[0] <= last[1]:  # overlapping or touching
                merged[-1] = (last[0], max(last[1], interval[1]))  # merge
            else:
                merged.append(interval)
    return merged

# Example:
intervals = [(0, 10), (12, 15), (15, 25)]
print(merge_intervals(intervals))

[(0, 10), (12, 25)]

In [116]:
from src.utils.common import merge_intervals

ImportError: cannot import name 'merge_intervals' from 'src.utils.common' (/home/mojtaba.kananisarche/Zh/src/utils/common.py)

In [41]:
a.loc[0]

,file_name,path,total_frames,start_frame,end_frame
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,0,1000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,1000,2000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,2000,3000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,3000,4000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,4000,5000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,5000,6000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,6000,7000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,7000,8000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,8000,9000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,9000,10000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,10000,11000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,11000,12000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,12000,13000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,13000,14000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,14000,15000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,15000,16000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,16000,17000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,17000,18000
0,video_info_1.csv,/work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...,18156,18000,18156

In [154]:
dg.data

   X    y                                             g
0     2.0  1_01_0_30fps_brightness_alpha0.8_beta-10.csv
1     2.0  1_01_0_30fps_brightness_alpha0.8_beta-10.csv
2     2.0  1_01_0_30fps_brightness_alpha0.8_beta-10.csv
3     2.0  1_01_0_30fps_brightness_alpha0.8_beta-10.csv
4     2.0  1_01_0_30fps_brightness_alpha0.8_beta-10.csv
5     2.0  1_01_0_30fps_brightness_alpha0.8_beta-10.csv
6     6.5  1_01_5_30fps_brightness_alpha0.8_beta-10.csv
7     6.5  1_01_5_30fps_brightness_alpha0.8_beta-10.csv
8     6.5  1_01_5_30fps_brightness_alpha0.8_beta-10.csv
9     6.5  1_01_5_30fps_brightness_alpha0.8_beta-10.csv
10    6.5  1_01_5_30fps_brightness_alpha0.8_beta-10.csv
11    6.5  1_01_5_30fps_brightness_alpha0.8_beta-10.csv

In [147]:
dg.__getitem__(1)

2025-04-22 05:22:39,437 - INFO - Loaded file: /work/long_lab/Mojtaba/data/UTA/1.3.2-augmented_embedded_preprocessed/brightness_alpha0.8_beta-10/1_01_10_30fps_brightness_alpha0.8_beta-10_preprocessed.csv, data shape: (18027, 135)

,X,y,g
7,"[[6.5, 1.418, 0.618, 0.09, -0.28, 0.878, 1.212...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
8,"[[6.5, 1.693, 1.159, -0.187, -0.224, 0.834, 1....",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
9,"[[6.5, 0.975, 0.407, 0.227, -0.552, 1.425, 0.6...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
10,"[[6.5, 1.078, 0.301, -0.296, 0.095, 1.409, 0.7...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
11,"[[6.5, 1.022, 0.204, -0.076, -0.152, 0.835, 0....",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
12,"[[8.5, 0.723, 0.484, -0.139, 0.282, 1.075, 0.4...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
13,"[[8.5, 1.365, 0.639, -0.165, 0.032, 0.733, 0.5...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv

In [148]:
dg.data

,X,y,g
0,"[[2.0, 0.804, 0.005, 0.232, 0.04, 0.599, 1.208...",2.0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv
1,"[[2.0, 0.975, 0.315, 0.186, 0.484, 1.249, 0.43...",2.0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv
2,"[[2.0, -0.137, 0.268, 0.413, 0.714, 1.186, -0....",2.0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv
3,"[[2.0, 0.703, 0.149, 0.192, 0.053, 1.823, 0.55...",2.0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv
4,"[[2.0, 0.237, 0.167, -0.129, 0.26, 1.162, 0.26...",2.0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv
5,"[[2.0, 0.536, 0.584, 0.227, 0.304, 0.851, 0.31...",2.0,1_01_0_30fps_brightness_alpha0.8_beta-10.csv
6,"[[6.5, 1.412, 0.829, -0.153, -0.436, 1.186, 0....",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
7,"[[6.5, 1.418, 0.618, 0.09, -0.28, 0.878, 1.212...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
8,"[[6.5, 1.693, 1.159, -0.187, -0.224, 0.834, 1....",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
9,"[[6.5, 0.975, 0.407, 0.227, -0.552, 1.425, 0.6...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
10,"[[6.5, 1.078, 0.301, -0.296, 0.095, 1.409, 0.7...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
11,"[[6.5, 1.022, 0.204, -0.076, -0.152, 0.835, 0....",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
12,"[[8.5, 0.723, 0.484, -0.139, 0.282, 1.075, 0.4...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
13,"[[8.5, 1.365, 0.639, -0.165, 0.032, 0.733, 0.5...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
14,"[[8.5, -0.284, -0.589, 0.133, -0.255, 2.441, -...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
15,"[[8.5, 1.099, -0.034, 0.45, 0.533, 1.466, 0.14...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
16,"[[8.5, 1.115, 0.46, 0.475, -0.145, 1.436, 0.11...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
17,"[[8.5, 1.565, 0.08, 0.382, 0.291, 1.759, 0.405...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv

In [149]:
dg.stash

,X,y,g
14,"[[8.5, -0.284, -0.589, 0.133, -0.255, 2.441, -...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
15,"[[8.5, 1.099, -0.034, 0.45, 0.533, 1.466, 0.14...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
16,"[[8.5, 1.115, 0.46, 0.475, -0.145, 1.436, 0.11...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv
17,"[[8.5, 1.565, 0.08, 0.382, 0.291, 1.759, 0.405...",8.5,1_01_10_30fps_brightness_alpha0.8_beta-10.csv

In [33]:
for (X, y, g) in zip(a1, a2, a3):
    print(X, y, g)
    break

[[ 2.     0.804  0.005 ...  0.205 -1.507 -0.229]
 [ 2.     0.522 -0.369 ...  0.199 -1.104 -0.297]
 [ 2.     0.492 -0.019 ...  1.232 -0.433  0.135]
 ...
 [ 2.     0.619  0.678 ...  0.419 -1.322  0.369]
 [ 2.     0.562  0.629 ...  0.454 -1.341  0.35 ]
 [ 2.     0.792  0.627 ...  0.625 -1.295  0.273]] 2.0 1_01_0_30fps_brightness_alpha0.8_beta-10.csv

In [40]:
a2[0]

np.float64(2.0)

In [25]:
dg

NameError: name 'dg' is not defined

In [ ]:
keras.Sequential()
import inspect

print(inspect.getfile(Sequence))

/home/mojtaba.kananisarche/.conda/envs/.cvenv/lib/python3.9/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py

In [161]:
dg.stash.sample(len(dg.stash))

,X,y,g
8,"[[6.5, 1.693, 1.159, -0.187, -0.224, 0.834, 1....",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
9,"[[6.5, 0.975, 0.407, 0.227, -0.552, 1.425, 0.6...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
10,"[[6.5, 1.078, 0.301, -0.296, 0.095, 1.409, 0.7...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
7,"[[6.5, 1.418, 0.618, 0.09, -0.28, 0.878, 1.212...",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv
11,"[[6.5, 1.022, 0.204, -0.076, -0.152, 0.835, 0....",6.5,1_01_5_30fps_brightness_alpha0.8_beta-10.csv

In [ ]:
data = pd.read_csv(os.path.join(input_path, 'video_info_1.csv'))

In [73]:
popped, remaining = pop_row(data, slice(0,5))

In [74]:
popped

                                                path  total_frames
0  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18156
1  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18362
2  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18519
3  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         19954
4  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         16820

In [75]:
remaining

                                                   path  total_frames
5     /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18222
6     /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         15010
7     /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18481
8     /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18729
9     /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18471
...                                                 ...           ...
1570  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18206
1571  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         17645
1572  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18081
1573  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         20620
1574  /work/long_lab/Mojtaba/data/UTA/1.3.2-augmente...         18333

[1570 rows x 2 columns]

In [90]:
# %cd '/home/mojtaba.kananisarche/'

# from Zh.src.utils.load_data import load_data
# import numpy as np
# import pandas as pd
# from typing import List, Optional, Tuple, Optional
# from Zh.src.utils.file_folder import create_folders
# import os
# import json
# import pandas as pd
# import dataframe_image as dfi
# from Zh.src.utils.visualize_results import confusion_matrix_results, table_results

In [91]:
# path = "/home/mojtaba.kananisarche/Zh/outputs/2025-04-20|09:08:09|RNN_FACENET_5CV"

In [92]:
# data = table_results(
# results_directory_path  = path,
# output_directory_path   = None,
# output_file_path_prefix = 'results',
# cmap                    = "Blues",
# reverse_cmap            = False,
# header_1_bg_color       = 'silver',
# header_1_text_color     = 'black',
# header_2_bg_color       = 'darkgrey',
# header_2_text_color     = 'black',
# maximum_tries           = 1,
# slice_or_video          = 'video', #slice, video
# video_voting_method     = 'class_average', #majority, class_average, average
# height                  = 2,
# width                   = 5,
# )

In [93]:
# data = confusion_matrix_results(
#     results_directory_path  = path,
#     unique_classes          = [2, 6.5, 8.5],
#     output_directory_path   = None,
#     output_file_name_prefix = "results",
#     slice_or_video          = 'slice',     #slice, video
#     video_voting_method     = 'average',   #majority, class_average, average
#     index                   = -1,          # positive for any index and negative for all
#     split                   = "all",       # train, val, test, all
#     cmap                    = "Greys",
#     maximum_tries           = 5,
#     corner_text_color       = "white",
#     corner_bg_color         = "IndianRed",
#     pred_true_text_color    = "black",
#     pred_true_bg_color      = "silver",
#     labels_bg_color         = "beige",
#     labels_text_color       = "black",
#     height                  = 5,
#     width                   = None,
# )